version: "3"

services:
    nginx:
        build:
            context: ./requirements/nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - mynetwork
        restart: always
        volumes:
            - "php_nginx:/var/www/html"
        container_name: nginx

    wordpress:
        build:
            context: ./requirements/wordpress
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - mynetwork
        restart: always
        env_file:
          - .env
        volumes:
            - "php_nginx:/var/www/html"
        container_name: wordpress

    mariadb:
        build:
            context: ./requirements/mariadb
        networks:
            - mynetwork
        restart: always
        volumes:
            - "db:/var/lib/mysql"
        env_file:
            - .env
        container_name: mariadb
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        build:
            context: ./requirements/bonus/redis
        ports:
            - "6379:6379"
        networks:
            - mynetwork
        restart: always
        container_name: redis

    adminer:
        build:
            context: ./requirements/bonus/adminer
        depends_on:
            - wordpress
        networks:
            - mynetwork
        container_name: adminer
        volumes:
            - "php_nginx:/var/www/html"
    ftp:
        build:
            context: ./requirements/bonus/ftp
        depends_on:
            - wordpress
        networks:
            - mynetwork
        restart: always
        container_name: ftp
        volumes:
            - "php_nginx:/ftp"
        ports:
            - "21:21"
            - "20:20"

networks:
    mynetwork:

volumes:
    php_nginx:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/sgoffaux/data/php_nginx
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/sgoffaux/data/db
