version: "3"

services:
    nginx:
        build:
            context: ./requirements/nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - mynetwork
        restart: always
        volumes:
            - "php_nginx:/var/www/html"
        container_name: nginx

    wordpress:
        build:
            context: ./requirements/wordpress
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - mynetwork
        restart: always
        env_file:
          - .env
        volumes:
            - "php_nginx:/var/www/html"
        container_name: wordpress

    mariadb:
        build:
            context: ./requirements/mariadb
        networks:
            - mynetwork
        restart: always
        volumes:
            - "db:/var/lib/mysql"
        env_file:
            - .env
        container_name: mariadb
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        build:
            context: ./bonus/redis
        ports:
            - "6379:6379"
        networks:
            - mynetwork
        restart: always
        container_name: redis

    adminer:
        build:
            context: ./bonus/adminer
        depends_on:
            - wordpress
        networks:
            - mynetwork
        container_name: adminer
        volumes:
            - "php_nginx:/var/www/html"
    ftp:
        build:
            context: ./bonus/ftp
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - mynetwork
        restart: always
        container_name: ftp
        volumes:
            - "php_nginx:/ftp"
        ports:
            - "0.0.0.0:20:20"
            - "0.0.0.0:21:21"
            - "21100-21110:21100-21110"
    express:
        build:
            context: ./bonus/express
        networks:
            - mynetwork
        restart: always
        container_name: express
        ports:
            - "80:80"
    # grafana:
    #     build:
    #         context: ./bonus/grafana
    #     networks:
    #         - mynetwork
    #     restart: always
    #     container_name: grafana
    #     ports:
    #         - "3000:3000"
    cadvisor:
        build:
            context: ./bonus/cadvisor
        networks:
            - mynetwork
        restart: always
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        ports:
            - "7000:7000"

networks:
    mynetwork:

volumes:
    php_nginx:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${SUDO_USER}/data/php_nginx
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${SUDO_USER}/data/db
